---
- hosts: "{{ variable_host | default('webservers') }}"
  vars_files:
    - vars.yaml
  become: yes
  become_method: sudo
  remote_user: '{{ user }}'

  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day 
    when: anisble_facts['os_family'] == "Debian"

  - name: install dependencies 
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - openjdk-11-jdk
      - unzip
      - tree
      - python3-pip
    when: anisble_facts['os_family'] == "Debian"

  - name: install dependencies 
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - openjdk-11-jdk
      - unzip
      - tree
      - python3-pip
    when: anisble_facts['os_family'] == "rhel"

  - name: add tomcat group
    group:
      name: tomcat

  - name: add tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /usr/share/tomcat
      createhome: no

  - name: create /opt/tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755
      owner: tomcat
      group: tomcat      
      recurse: yes
  
  - name: download & unarchive
    unarchive:
      src: '{{ tomcat_url }}'
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Copy Tomcat service from local to remote
    copy:
       src: tomcat.service
       dest: /etc/systemd/system/
       mode: 0755
       

  - name: Start and enable Tomcat service
    systemd:
      name: tomcat
      state: started
      enabled: true
      daemon_reload: true
