name: "Configure Web Servers"
on:
  workflow_dispatch:
    
jobs:
  setup:
    runs-on: self-hosted
    
    env:
      RESOURCE_GROUP: "petclinic-rg"
      VM_TAG: "web"
    steps:
      - name: Checkout the code 
        uses: actions/checkout@v3    
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Prepare Host file
        id: prepare-hosts
        run: |
          echo '[webservers]' > $HOME/hosts
          az vm list --resource-group $RESOURCE_GROUP --show-details \
          --query "[?contains(name, '$VM_TAG')].[privateIps]" -otsv >> $HOME/hosts
          cat $HOME/hosts
      - name: Run ansible playbook
        run: |
          cd Ansible
          ansible-playbook -i $HOME/hosts tomcat_playbook.yaml --private-key $HOME/id_az
          